-- Reference migration: production schema updates are applied automatically on startup
-- via migratePostgresLeadsPhoneMatchKey() in db.js (add column, backfill, dedupe, drop old unique, new index).
--
-- phone_match_key: tail-10 digit key (or full digit string when fewer than 10 digits), aligned with dialer analytics.
-- UNIQUE (client_key, phone_match_key) WHERE phone_match_key IS NOT NULL supersedes UNIQUE (client_key, phone).
